# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'category_row_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(144, 180)
        Form.setMaximumSize(QtCore.QSize(144, 190))
        Form.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(Form)
        self.title.setStyleSheet("")
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.image = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(130, 80))
        self.image.setText("")
        self.image.setObjectName("image")
        self.verticalLayout_2.addWidget(self.image)
        self.description = QtWidgets.QLabel(Form)
        self.description.setStyleSheet("")
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout_2.addWidget(self.description)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setProperty("class", _translate("Form", "materialcard"))
        self.title.setText(_translate("Form", "Sensor Name"))
        self.image.setProperty("class", _translate("Form", "materialcard-image"))
        self.description.setText(_translate("Form", "-"))
        self.description.setProperty("class", _translate("Form", "category-description"))
