# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expt_row.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 146)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(300, 146))
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MyFrame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MyFrame.sizePolicy().hasHeightForWidth())
        self.MyFrame.setSizePolicy(sizePolicy)
        self.MyFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MyFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MyFrame.setObjectName("MyFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MyFrame)
        self.gridLayout_2.setContentsMargins(3, 3, 0, 3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title = QtWidgets.QLabel(self.MyFrame)
        self.title.setStyleSheet("")
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 0, 1, 2)
        self.description = QtWidgets.QLabel(self.MyFrame)
        self.description.setStyleSheet("")
        self.description.setScaledContents(True)
        self.description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.gridLayout_2.addWidget(self.description, 1, 0, 1, 1)
        self.image = QtWidgets.QLabel(self.MyFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(120, 120))
        self.image.setText("")
        self.image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.image.setObjectName("image")
        self.gridLayout_2.addWidget(self.image, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 10)
        self.gridLayout.addWidget(self.MyFrame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setProperty("class", _translate("Form", "materialsubcard"))
        self.title.setText(_translate("Form", "Sensor Name"))
        self.description.setText(_translate("Form", "-"))
        self.description.setProperty("class", _translate("Form", "expt-description"))
        self.image.setProperty("class", _translate("Form", "expt-image"))
