# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_visual.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 472)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/control/kuttypy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log.sizePolicy().hasHeightForWidth())
        self.log.setSizePolicy(sizePolicy)
        self.log.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.log.setFont(font)
        self.log.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.log.setObjectName("log")
        self.gridLayout_2.addWidget(self.log, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logLabel.sizePolicy().hasHeightForWidth())
        self.logLabel.setSizePolicy(sizePolicy)
        self.logLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.logLabel.setFont(font)
        self.logLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.logLabel.setObjectName("logLabel")
        self.horizontalLayout.addWidget(self.logLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.termFrame = QtWidgets.QFrame(self.centralwidget)
        self.termFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.termFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.termFrame.setObjectName("termFrame")
        self.termLayout = QtWidgets.QVBoxLayout(self.termFrame)
        self.termLayout.setContentsMargins(0, 0, 0, 0)
        self.termLayout.setSpacing(0)
        self.termLayout.setObjectName("termLayout")
        self.mpFrame = QtWidgets.QFrame(self.termFrame)
        self.mpFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mpFrame.setObjectName("mpFrame")
        self.mpLayout = QtWidgets.QVBoxLayout(self.mpFrame)
        self.mpLayout.setContentsMargins(0, 0, 0, 0)
        self.mpLayout.setSpacing(0)
        self.mpLayout.setObjectName("mpLayout")
        self.mpLabel = QtWidgets.QLabel(self.mpFrame)
        self.mpLabel.setText("")
        self.mpLabel.setObjectName("mpLabel")
        self.mpLayout.addWidget(self.mpLabel)
        self.termLayout.addWidget(self.mpFrame)
        self.gridLayout_2.addWidget(self.termFrame, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KuttyPy Interactive Console"))
        self.logLabel.setText(_translate("MainWindow", "KUTTYPY VISUAL CODING"))
from . import resplus_rc
