# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 683)
        MainWindow.setStyleSheet("")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log.sizePolicy().hasHeightForWidth())
        self.log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.log.setFont(font)
        self.log.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.log.setObjectName("log")
        self.gridLayout_2.addWidget(self.log, 3, 0, 2, 2)
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setObjectName("tabs")
        self.playground = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playground.sizePolicy().hasHeightForWidth())
        self.playground.setSizePolicy(sizePolicy)
        self.playground.setObjectName("playground")
        self.gridLayout = QtWidgets.QGridLayout(self.playground)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.playground)
        self.tabWidget.setObjectName("tabWidget")
        self.photoTab = QtWidgets.QWidget()
        self.photoTab.setObjectName("photoTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.photoTab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.photoTab)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(64, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tabWidget.addTab(self.photoTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.registerLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.registerLayout.setContentsMargins(0, 0, 0, 10)
        self.registerLayout.setSpacing(3)
        self.registerLayout.setObjectName("registerLayout")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, 4, -1, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/control/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.registerLayout.addWidget(self.frame)
        self.registerList = QtWidgets.QListWidget(self.tab_2)
        self.registerList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.registerList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.registerList.setObjectName("registerList")
        self.registerLayout.addWidget(self.registerList)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabs.addTab(self.playground, "")
        self.examples = QtWidgets.QWidget()
        self.examples.setObjectName("examples")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.examples)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(3)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolButton = QtWidgets.QToolButton(self.examples)
        self.toolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/control/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_3.addWidget(self.toolButton, 0, 2, 1, 1)
        self.exampleList = QtWidgets.QComboBox(self.examples)
        self.exampleList.setObjectName("exampleList")
        self.gridLayout_3.addWidget(self.exampleList, 0, 0, 1, 1)
        self.userCode = QtWidgets.QPlainTextEdit(self.examples)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.userCode.setFont(font)
        self.userCode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.userCode.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.userCode.setTabStopWidth(30)
        self.userCode.setBackgroundVisible(False)
        self.userCode.setCenterOnScroll(False)
        self.userCode.setProperty("class", "")
        self.userCode.setObjectName("userCode")
        self.gridLayout_3.addWidget(self.userCode, 1, 0, 1, 3)
        self.toolButton_2 = QtWidgets.QToolButton(self.examples)
        self.toolButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/control/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_3.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.tabs.addTab(self.examples, "")
        self.gridLayout_2.addWidget(self.tabs, 0, 0, 1, 2)
        self.enableLog = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableLog.sizePolicy().hasHeightForWidth())
        self.enableLog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.enableLog.setFont(font)
        self.enableLog.setChecked(True)
        self.enableLog.setObjectName("enableLog")
        self.gridLayout_2.addWidget(self.enableLog, 6, 0, 1, 1)
        self.clearLog = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearLog.sizePolicy().hasHeightForWidth())
        self.clearLog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.clearLog.setFont(font)
        self.clearLog.setChecked(True)
        self.clearLog.setObjectName("clearLog")
        self.gridLayout_2.addWidget(self.clearLog, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pcdock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pcdock.sizePolicy().hasHeightForWidth())
        self.pcdock.setSizePolicy(sizePolicy)
        self.pcdock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.pcdock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.pcdock.setObjectName("pcdock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.pclayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.pclayout.setObjectName("pclayout")
        self.pcdock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.pcdock)
        self.pddock = QtWidgets.QDockWidget(MainWindow)
        self.pddock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.pddock.setAllowedAreas(QtCore.Qt.RightDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.pddock.setObjectName("pddock")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.pdlayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_5)
        self.pdlayout.setObjectName("pdlayout")
        self.pddock.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.pddock)
        self.padock = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.padock.sizePolicy().hasHeightForWidth())
        self.padock.setSizePolicy(sizePolicy)
        self.padock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.padock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea)
        self.padock.setObjectName("padock")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.palayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_6)
        self.palayout.setObjectName("palayout")
        self.padock.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.padock)
        self.pbdock = QtWidgets.QDockWidget(MainWindow)
        self.pbdock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.pbdock.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.pbdock.setObjectName("pbdock")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.pblayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_7)
        self.pblayout.setObjectName("pblayout")
        self.pbdock.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.pbdock)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.toolButton.clicked.connect(MainWindow.runCode)
        self.tabs.currentChanged['int'].connect(MainWindow.tabChanged)
        self.toolButton_2.clicked.connect(MainWindow.abort)
        self.exampleList.currentIndexChanged['QString'].connect(MainWindow.loadExample)
        self.pushButton.clicked.connect(MainWindow.newRegister)
        self.checkBox.clicked['bool'].connect(MainWindow.userRegistersAutoRefresh)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KuttyPy Interactive Console"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/control/kpys.jpeg\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.photoTab), _translate("MainWindow", "Photo"))
        self.pushButton.setText(_translate("MainWindow", "Add A New Register"))
        self.checkBox.setText(_translate("MainWindow", "Auto-Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Fiddle with Registers"))
        self.tabs.setTabText(self.tabs.indexOf(self.playground), _translate("MainWindow", "Playground"))
        self.userCode.setPlainText(_translate("MainWindow", "import time\n"
"from kuttyPy import *\n"
"setReg(DDRD,255)\n"
"\n"
"for a in range(5):   #Run this loop 5 times. \n"
"    setReg(PORTD, 255)\n"
"    time.sleep(0.5)\n"
"    setReg(PORTD, 0)\n"
"    time.sleep(0.5)"))
        self.tabs.setTabText(self.tabs.indexOf(self.examples), _translate("MainWindow", "Code Snippets"))
        self.enableLog.setText(_translate("MainWindow", "Enabled"))
        self.clearLog.setText(_translate("MainWindow", "Auto-Clear"))
        self.label_2.setText(_translate("MainWindow", "Monitor registers being read and set during each operation"))
        self.pcdock.setWindowTitle(_translate("MainWindow", "PORT C"))
        self.pddock.setWindowTitle(_translate("MainWindow", "PORT D"))
        self.padock.setWindowTitle(_translate("MainWindow", "PORT A"))
        self.pbdock.setWindowTitle(_translate("MainWindow", "PORT B"))

from . import res_rc
