site_name: KuttyPy Graphical Interface Documentation
theme:
  name: 'material'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/kuttypy.png
  favicon: 'images/favicon.png'
  features:
    - navigation.footer
    - content.code.copy
  icon:
    annotation: material/arrow-right-circle 
 

#theme: 'readthedocs'
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - attr_list
    - wikilinks
    - codehilite:
        linenums: False
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
       preserve_tabs: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde

extra_css: ["assets/main.css"]
site_favicon: 'images/favicon.ico'

extra:
  palette:
      primary: '#087da1'
      accent: '#00a889'
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://x.com/csparkresearch
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/csparkresearch
    - icon: fontawesome/brands/github
      link: https://github.com/csparkresearch


plugins:
   - search
   - exclude-search:
      exclude:
        - workshopnano.md
        - boards.md
   - table-reader
   - material/social:
      cards: true
      cards_font: Roboto
   #- page-to-pdf


repo_name: 'csparkresearch/kuttypy-gui'
repo_url: 'https://github.com/csparkresearch/kuttypy-gui'
copyright: 'Copyright © 2019 <a href="https://csparkresearch.in">CSpark Research</a>'

google_analytics:
  - 'UA-67472997-4'
  - 'auto'

nav:
  - Home: 'index.md'
  - Getting Started:
      - 'Installation': 'installation.md'
      - 'Software': 'software.md'
  - I/O and Peripherals:
      - 'Basic I/O': 'io.md'
      - '8 Channel Voltmeter': 'adc.md'
      - 'Stepper Motors': 'stepper.md'
  - I2C Sensors: 'sensors.md'
  - Programming - Python:
      - 'Introduction': 'programming/intro.md'
      - 'Basic I/O': 'programming/basics.md'
      - 'I2C and Sensors': 'programming/i2c.md'
  - Programming - C: 'programming/c.md'
  - Projects:
      - 'R2R DAC Wavegen': 'programming/r2r_wavegen.md'
      - 'Optics: Malus Law': 'malus.md'
  - KuttyPy Hardware:
      - 'Design': 'hw.md'
      - 'Firmware': 'boot.md'
      - 'Enclosures': 'enclosures.md'
#  - Nano Tutorial: 'workshopnano.md'
  - 2 Hour Tutorial: 'workshop.md'
#  - Arduino Boards : 'boards.md'

